[atom]
name = "dev"

[fetch.pkgs]
args   = [{}]
import = true
name   = "nixpkgs"

[fetch.fenix]
args   = [{ pkgs = true }]
import = true
name   = "fenix"

[std]
features = ["lib"]

[backend.nix]
fetcher = "npins"

[fetcher.npins]
root = "npins"
