edition                  = "2021"
newline_style            = "unix"
use_field_init_shorthand = true
use_try_shorthand        = true

unstable_features = true

comment_width               = 100
condense_wildcard_suffixes  = true
error_on_line_overflow      = true
format_code_in_doc_comments = true
format_macro_bodies         = true
format_macro_matchers       = true
format_strings              = true
group_imports               = "StdExternalCrate"
imports_granularity         = "Module"
match_block_trailing_comma  = true
normalize_doc_attributes    = true
reorder_impl_items          = true
style_edition               = "2024"
wrap_comments               = true
