[build]
command = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env && rm -rf .cargo && cargo doc -p atom --no-deps"
publish = "target/doc"

[[redirects]]
force  = true
from   = "/"
status = 301
to     = "/atom/"
