[package]
edition = "2021"
name    = "resolve"
version = "0.1.0"

[dependencies]
anyhow.workspace    = true
serde.workspace     = true
toml_edit.workspace = true
url.workspace       = true

hex = "^0.4"
